apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: buildkite-agent
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: buildkite-agent
   spec:
     containers:
       - name: buildkite-agent
         image: buildkite/agent
         imagePullPolicy: Always
         securityContext:
           privileged: true
         env:
           - name: BUILDKITE_AGENT_TOKEN
             valueFrom: {secretKeyRef: {name: buildkite-agent, key: token}}
         volumeMounts:
           - name: docker-binary
             mountPath: /usr/bin/docker
           - name: docker-socket
             mountPath: /var/run/docker.sock
           - name: ssh-key
             subPath: id_rsa
             mountPath: /root/.ssh/id_rsa
             readOnly: true
           - name: ssh-key
             subPath: id_rsa.pub
             mountPath: /root/.ssh/id_rsa.pub
             readOnly: true

       - name: sbt-install
         image: bigtruedata/sbt
         volumeMounts:
           - name: work-dir
           - mountPath: /data/sbt

     volumes:
       - name: work-dir
         source:
           emptyDir: {}
       - name: docker-binary
         hostPath: {path: /usr/bin/docker}
       - name: docker-socket
         hostPath: {path: /var/run/docker.sock}
       - name: ssh-key
         secret:
           secretName: buildkite-agent-ssh
           defaultMode: 256
