#[START swagger]
swagger: "2.0"
info:
  description: "A Play Framework Service in Google Cloud Endpoints"
  title: "Play Service in GCP Endpoints"
  version: "1.0.0"
host: "play-service.endpoints.tardis-1.cloud.goog"
# [END swagger]
basePath: "/"
consumes:
- "application/json"
produces:
- "application/text"
schemes:
- "https"
paths:
  "/count":
    get:
      description: "get a count"
      operationId: "count"
      produces:
      - "application/text"
      responses:
        200:
          description: "Count"
      security:
        - api_key: []

securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
