steps:
  - label: Build
    command: scripts/build
    timeout_in_minutes: 10
    agents:
      queue: default
  - wait
  - label: Dockerize
    command: scripts/dockerize
    timeout_in_minutes: 5
    agents:
      queue: default
  - wait
  - label: Package
    command: scripts/package
    timeout_in_minutes: 5
    agents:
      queue: default
  - wait
