steps:
  - label: Build
    command: scripts/build
    timeout_in_minutes: 10
    agents:
      queue: default
  - wait
  - label: Package
    command: scripts/package
    timeout_in_minutes: 5
    artifact_paths: target/aws/fuhgavi*.zip
    agents:
      queue: default
  - wait
