steps:
  - label: Build
    command: scripts/build
    timeout_in_minutes: 10
    agents:
      queue: default
  - wait
  - label: Dockerize
    command: scripts/dockerize
    timeout_in_minutes: 5
    agents:
      queue: default
  - wait
  - label: Package
    command: scripts/package
    timeout_in_minutes: 5
    agents:
      queue: default
  - wait
  - label: Generate Endpoints
    command: scripts/generate_endpoints
    timeout_in_minutes: 5
    agents:
      queue: default
  - wait
    - label: Deploy to Dev
      command: scripts/dev_deploy
      timeout_in_minutes: 5
      agents:
        queue: default
  - wait
